version: "3.9"
services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'cultureamp/batch-steps']
    volumes:
      - ".:/plugin:ro"

  tests:
    build: .
    volumes:
      - ".:/plugin:ro"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"
