name: batch-steps
description: Batch Steps with additional arguments.
author: https://github.com/tobig77
requirements:
  - docker
configuration:
  properties:
    batch-size:
      type: integer
    group-name:
      type: string
    group-label:
      type: string
    step-template:
      type: string
    variable-file:
      type: string
    wait-for-batch:
      type: boolean
    variable-name:
      type: [string, array]
