name: batch-steps
description: Batch Steps with additional arguments.
author: https://github.com/tobig77
requirements:
  - docker
configuration:
  properties:
    batch-size:
      type: integer
    step-template:
      type: string
    variable-file:
      type: string
    variable-name:
      type: [string, array]
